name = "DynamicProgrammingExamples"
uuid = "ec18ebbb-5983-4057-999b-4b851b7ab46d"
authors = ["Isaac Leeson <isaacleeson@proton.me> and contributors"]
version = "1.0.0-DEV"

[deps]
CommonSolve = "38540f10-b2f7-11e9-35d8-d573e4eb0ff2"
DynamicProgrammingGPU = "48fc1f4b-edff-4ab5-bb62-9a666f40f0b0"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
